{% set name = "asebytes" %}
{% set version = "0.2.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asebytes-{{ version }}.tar.gz
  sha256: 98b1f91c77941f829e552a1fb5b19451d815c75c2495636d73717c359d12dcb4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9.6,<0.10.0
    - pip
  run:
    - python >={{ python_min }}
    - ase >=3.26.0
    - python-lmdb >=1.7.5
    - msgpack-python >=1.1.2
    - msgpack-numpy >=0.4.8

test:
  imports:
    - asebytes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: LMDB-based storage for ASE.
  home: https://github.com/zincware/asebytes
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
